management:
    endpoints:
        web:
            exposure:
                include: refresh,health,info
server:
    port: 8888
spring:
    cloud:
        config:
            server:
                git:
                    default-label: main
                    uri: https://github.com/your-username/pharmacy-config-repo

resilience4j:
    circuitbreaker:
        instances:
            warehouseCB:
                failure-rate-threshold: 50
                wait-duration-in-open-state: 20s
                sliding-window-type: COUNT_BASED
                sliding-window-size: 10
                minimum-number-of-calls: 5
                permitted-number-of-calls-in-half-open-state: 3
    retry:
        instances:
            insuranceRetry:
                max-attempts: 3
                wait-duration: 2s
                retry-exceptions:
                    - java.net.ConnectException
                    - java.net.SocketTimeoutException
                    - org.springframework.web.reactive.function.client.WebClientRequestException
                    - java.lang.RuntimeException
    spring:
        mail:
            host: smtp.gmail.com
            port: 587
            username: ${EMAIL_USER}
            password: ${EMAIL_PASSWORD}
            properties:
                mail.smtp.auth: true
                mail.smtp.starttls.enable: true

        kafka:
            consumer:
                group-id: notification-group # QUAN TRỌNG: Phải khác inventory-group
                auto-offset-reset: earliest
                # Cấu hình tin cậy class OrderEvent tương tự inventory-service
