resilience4j:
    retry:
        instances:
            invoiceRetry:
                max-attempts: 3
                wait-duration: 2s
                retry-exceptions:
                    - java.net.ConnectException
                    - java.net.SocketTimeoutException
                    - org.springframework.web.client.ResourceAccessException

    ratelimiter:
        instances:
            invoiceRateLimiter:
                limit-for-period: 5
                limit-refresh-period: 10s
                timeout-duration: 0s

    circuitbreaker:
        instances:
            insuranceCB:
                failure-rate-threshold: 60
                sliding-window-type: COUNT_BASED
                sliding-window-size: 10
                minimum-number-of-calls: 5
                wait-duration-in-open-state: 20s
                permitted-number-of-calls-in-half-open-state: 3




management:
    endpoints:
        web:
            exposure:
                include: health,info,retries,ratelimiters